### ISSUE TITLE
Write xlsx file issues

### ISSUE THREAD

**Issue by chiragrlti** [millij/poi-object-mapper#24] opened 2019-12-12 14:01 UTC
The order of written data is not same as order of class property. If i want to write to an existing file that is not happening. It is deleting all the other sheets and formatting and simply dumping the data.

**Comment by millij** [comment] 2023-12-19 15:25
Possible duplicate of  #12

[@SheetColumn](https://github.com/millij/poi-object-mapper/blob/develop/src/main/java/io/github/millij/poi/ss/model/annotations/SheetColumn.java) annotation now (as of `3.0.0`) supports order as an additional property.

This order value is used to order the Headers when writing to files.

Other write issues are also fixed in the version `3.0.0`

**Closed by millij** 2023-12-19 15:25 UTC
Labels: bug
